services:
  - type: web
    name: telegram-forward-bot
    env: python
    plan: free   # oder starter (empfohlen gegen Sleep)
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    autoDeploy: true
